### PR TITLE
Fix flipped screen on T8SG Fixes #701

### LINKED ISSUE #701: Pull #694 made my t8sg LCD upsidedown and mirrored
@PhracturedBlue Pull #694 made my t8sg LCD upsidedown and mirrored.  I reverted that change and it seemed to fix it.  I don't have any other TXs to test against right now

### PR DESCRIPTION
**Pull request by PhracturedBlue**
Pull #694 flipped the t8sg screen.  This should put it back the way it belongs

### CODE REVIEW

File: src/target/drivers/display/spi/128x64x1_nt7538.c [hunk 1]
```diff
@@ -88,12 +91,17 @@ void LCD_Init()
...
     volatile int i = 0x8000;
     while(i) i--;
-    LCD_Cmd(0xAE);  //Display off
+    lcd_display(0); //Display Off
     LCD_Cmd(0xA6);  //Normal display
     LCD_Cmd(0xA4);  //All Points Normal
-    LCD_Cmd(0xEA);  //??
-    LCD_Cmd(0xA0);  //ADC Normal
-    LCD_Cmd(0xC4);  //Common Output Mode Scan Rate
+    LCD_Cmd(0xA0);  //Set SEG Direction (Normal)
```
Comment (PhracturedBlue) [inline src/target/drivers/display/spi/128x64x1_nt7538.c]: Lint Error:
```
94:  At least two spaces is best between code and comments  
94:  Should have a space between // and comment  
97:  Should have a space between // and comment  
```

File: src/target/drivers/display/spi/128x64x1_nt7538.c [hunk 2]
```diff
@@ -88,12 +91,17 @@ void LCD_Init()
...
+    if (HAS_LCD_FLIPPED) {
+        LCD_Cmd(0xC8);  //Set COM Direction (Reversed)
+        LCD_Cmd(0xA2);  //Set The LCD Display Driver Voltage Bias Ratio (1/9)
+    } else {
+        LCD_Cmd(0xEA);  //??
+        LCD_Cmd(0xC4);  //Common Output Mode Scan Rate
```
Comment (PhracturedBlue) [inline src/target/drivers/display/spi/128x64x1_nt7538.c]: Lint Error:
```
99:  Should have a space between // and comment  
100:  Should have a space between // and comment  
103:  Should have a space between // and comment  
```

File: src/target/drivers/display/spi/128x64x1_nt7538.c [hunk 3]
```diff
@@ -88,19 +91,24 @@ void LCD_Init()
...
+        LCD_Cmd(0xA2);  // Set The LCD Display Driver Voltage Bias Ratio (1/9)
+    } else {
+        LCD_Cmd(0xEA);  // ??
+        LCD_Cmd(0xC4);  // Common Output Mode Scan Rate
+    }
+    LCD_Cmd(0x2C); // Power Controller:Booster ON
     i = 0x8000;
     while(i) i--;
-    LCD_Cmd(0x2E); //Power Controller: VReg ON
+    LCD_Cmd(0x2E); // Power Controller: VReg ON
```
Comment (PhracturedBlue) [inline src/target/drivers/display/spi/128x64x1_nt7538.c]: Lint Error:
```
105:  At least two spaces is best between code and comments  
108:  At least two spaces is best between code and comments  
```

File: src/target/drivers/display/spi/128x64x1_nt7538.c [hunk 4]
```diff
@@ -88,19 +91,24 @@ void LCD_Init()
...
     i = 0x8000;
     while(i) i--;
-    LCD_Cmd(0x2F); //Power Controller: VFollower ON
+    LCD_Cmd(0x2F); // Power Controller: VFollower ON
```
Comment (PhracturedBlue) [inline src/target/drivers/display/spi/128x64x1_nt7538.c]: Lint Error:
```
111:  At least two spaces is best between code and comments  
```
