### PR TITLE
Fix calibration (issue #574)

### LINKED ISSUE #574: Calibration is broken in master
after calibration, the stick value and swich value will not change anymore. @TheRealMoeder @PhracturedBlue

### PR DESCRIPTION
**Pull request by hexfet**
Run mixer calculations on timer after de-initializing protocol.  Ensures channel data is updated for functions like calibration.  Fixes #574 .

### CODE REVIEW

File: src/protocol/protocol.c [hunk 1]
```diff
@@ -121,6 +121,7 @@ void PROTOCOL_DeInit()
     CLOCK_StopTimer();
     if(Model.protocol != PROTOCOL_NONE && PROTOCOL_LOADED)
         PROTO_Cmds(PROTOCMD_DEINIT);
+    CLOCK_StartMixer(); // run mixer on timer so channels are updated for things like calibration
```
Comment (howard0su) [inline src/protocol/protocol.c]: I prefer putting the comments above the line, which is more common practice and also make the width of line small.

Comment (PhracturedBlue) [reply src/protocol/protocol.c]: I actually prefer this way because it makes it more likely the comment will be preserved if the line is moved.  But it isn't a strong rule
